<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.pih.openmrs</groupId>
		<artifactId>pihmalawi-emr</artifactId>
		<version>9.2.0-SNAPSHOT</version>
	</parent>

	<groupId>org.openmrs.module</groupId>
	<artifactId>pihmalawi-api</artifactId>
	<packaging>jar</packaging>
	<name>PIH Malawi Customizations API</name>
	<description>API project for PIH Malawi Customizations</description>

	<dependencies>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>coreapps-api</artifactId>
			<version>${coreappsVersion}</version>
		</dependency>

		<dependency>
			<groupId>net.sf.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>2.3</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>authentication-api</artifactId>
			<version>${authenticationVersion}</version>
			<type>jar</type>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>authenticationui-api</artifactId>
			<version>${authenticationuiVersion}</version>
			<type>jar</type>
			<scope>provided</scope>
		</dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>appui-api</artifactId>
            <version>${appuiVersion}</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>calculation-api</artifactId>
            <version>${calculationVersion}</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>emrapi-api</artifactId>
            <version>${emrapiVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>emrapi-api</artifactId>
            <version>${emrapiVersion}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs</groupId>
            <artifactId>event-api</artifactId>
            <version>${eventVersion}</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>fhir2-api</artifactId>
			<version>${fhir2Version}</version>
			<scope>provided</scope>
		</dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>htmlformentry-api</artifactId>
            <version>${htmlformentryVersion}</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>htmlformentryui-api</artifactId>
            <version>${htmlformentryuiVersion}</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>htmlwidgets-api</artifactId>
            <version>${htmlwidgetsVersion}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>idgen-api</artifactId>
            <version>${idgenVersion}</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>initializer-api</artifactId>
			<version>${initializerVersion}</version>
			<type>jar</type>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>initializer-api-2.2</artifactId>
			<version>${initializerVersion}</version>
			<type>jar</type>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>initializer-api-2.3</artifactId>
			<version>${initializerVersion}</version>
			<type>jar</type>
			<scope>provided</scope>
		</dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>metadatamapping-api</artifactId>
            <version>${metadatamappingVersion}</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>namephonetics-api</artifactId>
            <version>${namephoneticsVersion}</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>reporting-api</artifactId>
			<version>${reportingVersion}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>reporting-api</artifactId>
			<version>${reportingVersion}</version>
			<type>jar</type>
			<scope>test</scope>
			<classifier>tests</classifier>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>serialization.xstream-api</artifactId>
			<version>${serializationxstreamVersion}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>spa</artifactId>
			<version>${spaVersion}</version>
			<type>pom</type>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>uiframework-api</artifactId>
			<version>${uiframeworkVersion}</version>
			<scope>provided</scope>
		</dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>appframework-api</artifactId>
            <version>${appframeworkVersion}</version>
            <scope>provided</scope>
        </dependency>
		<dependency>
			<groupId>org.openmrs.api</groupId>
			<artifactId>openmrs-api</artifactId>
			<version>${openMRSVersion}</version>
			<type>jar</type>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.openmrs.api</groupId>
			<artifactId>openmrs-api</artifactId>
			<version>${openMRSVersion}</version>
			<type>jar</type>
			<scope>test</scope>
			<classifier>tests</classifier>
		</dependency>
		<dependency>
			<groupId>org.openmrs.test</groupId>
			<artifactId>openmrs-test</artifactId>
			<version>${openMRSVersion}</version>
			<type>pom</type>
			<scope>test</scope>
		</dependency>

        <dependency>
            <groupId>org.openmrs.contrib</groupId>
            <artifactId>testutils</artifactId>
            <version>${testutilsVersion}</version>
            <scope>test</scope>
        </dependency>

		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>legacyui-api</artifactId>
			<version>${legacyuiVersion}</version>
			<scope>provided</scope>
		</dependency>

		<!-- This is needed for appframework testing -->
		<dependency>
			<groupId>javax.el</groupId>
			<artifactId>javax.el-api</artifactId>
			<version>3.0.1-b06</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.el</artifactId>
			<version>3.0.1-b12</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<excludes>
					<exclude>**/*.xml</exclude>
					<exclude>**/*.properties</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*.xml</include>
					<include>**/*.properties</include>
				</includes>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
				<filtering>false</filtering>
				<excludes>
					<exclude>**/*.xml</exclude>
					<exclude>**/*.properties</exclude>
				</excludes>
			</testResource>
			<testResource>
				<directory>src/test/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*.xml</include>
					<include>**/*.properties</include>
				</includes>
			</testResource>
		</testResources>
	</build>
</project>
